title:            SASNUI | ZHAO
description:      这是一个叫三岁的人
url:              https://sansuiz.github.io/
permalink:        pretty
timezone:         Asia/Urumqi
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
